[package]
name = "const-cstr"
version = "0.3.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]
description = "Create static C-compatible strings from Rust string literals."
license = "MIT OR Apache-2.0"
repository = "https://github.com/cybergeek94/const-cstr"

